// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;


import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;
import edu.wpi.first.wpilibj.Joystick.*;
import edu.wpi.first.wpilibj.buttons.*;
import edu.wpi.first.wpilibj.*;
import frc.robot.subsystems.*;
import frc.robot.commands.*;





/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public Joystick leftJoystick;
public Joystick rightJoystick;
public JoystickButton moveLowerIntakeButton;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        rightJoystick = new Joystick(1);
        leftJoystick = new Joystick(0);
        
        Button Trigger = new edu.wpi.first.wpilibj.buttons.JoystickButton(rightJoystick, 1);
        Button button2 = new edu.wpi.first.wpilibj.buttons.JoystickButton(rightJoystick, 2);
        Button button3 = new edu.wpi.first.wpilibj.buttons.JoystickButton(rightJoystick, 3);
        Button button6 = new edu.wpi.first.wpilibj.buttons.JoystickButton(rightJoystick, 6);
        Button button7 = new edu.wpi.first.wpilibj.buttons.JoystickButton(rightJoystick, 7);
        Button button11 = new edu.wpi.first.wpilibj.buttons.JoystickButton(rightJoystick, 11);
        Button button10 = new edu.wpi.first.wpilibj.buttons.JoystickButton(rightJoystick, 10);
        Button button4 = new edu.wpi.first.wpilibj.buttons.JoystickButton(rightJoystick, 4);
      
        //spin up the shooter to speed, before feeding balls in
        button4.whileHeld(new StartShooter());

        
        //pulling the trigger will feed balls into an already spinning shooter, using lowerintake
        // upperintake and indexer
        Trigger.whileHeld(new runLowerIntake(-0.4));
        Trigger.whileHeld(new runUpperIntake(-0.4));
        Trigger.whileHeld(new RunIndexer(0.4));


        //run the intake and the feeders inwards to raise balls into the robot
        button2.whileHeld(new runUpperIntake(-0.4));
        button2.whileHeld(new runLowerIntake(-0.4));
        button2.whileHeld(new RunIntake(-0.2));


        //run the  intake and the feeders outwards to lower balls out of the robot
        button3.whileHeld(new runUpperIntake(0.4));
        button3.whileHeld(new runLowerIntake(0.4));
        button3.whileHeld(new RunIntake(0.2));
        button3.whileHeld(new RunIndexer(-0.4));

        //just run the lowerintake and intake out to spit out balls
        button6.whileHeld(new runLowerIntake(0.5));
        button6.whileHeld(new RunIntake(1));


        //just run the lowerintake and intake in to move balls closer to upperintake
        button7.whileHeld(new runLowerIntake(-0.5));
        button7.whileHeld(new RunIntake(-0.5));


        //just run the upper intake out to move balls towards lowerintake
        button11.whileHeld(new runUpperIntake(0.5));


        //just run the upper intake in to move balls towards indexer and shooter
        button10.whileHeld(new runUpperIntake(-0.5));
        
        
        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("RunDrivetrain", new RunDrivetrain());
        SmartDashboard.putData("RunIntake", new RunIntake(0.5));
        SmartDashboard.putData("crossInitiation", new crossInitiation());
        SmartDashboard.putData("doNothing", new doNothing());
        SmartDashboard.putData("Turnleft", new Turnleft(0.5));
        SmartDashboard.putData("Turnright", new Turnright(0.5));
        SmartDashboard.putData("autoMoveAround", new autoMoveAround()); 
        SmartDashboard.putData("crossAndGoBack", new crossAndGoBack());
        SmartDashboard.putData("goBackwards", new goBackwards(1));
        SmartDashboard.putData("toEnemyLoadingZoneFromLeft", new toEnemyLoadingZoneFromLeft());
        SmartDashboard.putData("toTargetZoneFromRight", new toTargetZoneFromRight());
        SmartDashboard.putData("goToOurTrenchFromRight", new goToOurTrenchFromRight());
        SmartDashboard.putData("goToEnemyTrenchFromLeft", new goToEnemyTrenchFromLeft());
        SmartDashboard.putData("goInFrontOfTargetZoneFromRight", new goInFrontOfTargetZoneFromRight());
        SmartDashboard.putData("goInFrontOfTargetZoneFromRightNGiveBalls", new goInFrontOfTargetZoneFromRightNGiveBalls());
        SmartDashboard.putData("goToRendevousFromLeft", new goToRendevousFromLeft());
        SmartDashboard.putData("releaseBallsAndGoToTrenchAndPickUp", new releaseBallsAndGoToTrenchAndPickUp());
        SmartDashboard.putData("releaseBallsAndGoToTrenchAndPickUpBallsFromRight", new releaseBallsAndGoToTrenchAndPickUpBallsFromRight());
        SmartDashboard.putData("goThroughRendevousPointFromLinedUpWithOurSide", new goThroughRendevousPointFromLinedUpWithOurSide());
        SmartDashboard.putData("goRightInFrontOfEnemySectorFromLinedUpWithRendevous", new goRightInFrontOfEnemySectorFromLinedUpWithRendevous() );
        SmartDashboard.putData("runlowerintake", new runLowerIntake(0.5));
        SmartDashboard.putData("runUpperIntake", new runUpperIntake(0.5));
        

        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
public Joystick getLeftjoystick() {
        return leftJoystick;
    }

public Joystick getRightJoystick() {
        return rightJoystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS




    public double GetLeftJoytickValue(){



        double left = leftJoystick.getRawAxis(1);
   
        return Math.signum(left)*Math.pow(left,2);

      
      }
      public double GetRightJoytickValue(){

        double Right = rightJoystick.getRawAxis(1);
   
        return Math.signum(Right)*Math.pow(Right,2);
      }
       
      public double GetYAxisValue(){
        double Yaxis=leftJoystick.getRawAxis(1);
        return Math.signum(Yaxis)*Math.pow(Yaxis,2);
        }
      public double GetXAxisValue(){
          double Xaxis=leftJoystick.getRawAxis(5);
          return Math.signum(Xaxis)*Math.pow(Xaxis,2);
    
      }
}

